### PR TITLE
Added NewMessageStream

### PR DESCRIPTION
**Pull request by mlitvin**
This enable easier mocking of Session and unit testing of packages
using govici

### CODE REVIEW

**Comment by enr0n** [comment]
Thanks for your PR.

You say this enables easier mocking and unit testing; do you have an example of this?

**Comment by mlitvin** [comment]
I have code that uses govici, and to unit test it I would like to mock vici.Session.
The natural thing would be to have (in my own library):

```go
type Session interface {
	Close() error
	CommandRequest(cmd string, msg *vici.Message) (*vici.Message, error)
	StreamedCommandRequest(cmd string, event string, msg *vici.Message) (*vici.MessageStream, error)
}
```
(Those are the methods that I'm using, so I don't need to mock other things)

However I cannot use this because in my package I cannot create a meaningful MessageStream (I can never set the messages inside of it).

Instead I had to to have

```go
type Session interface {
	Close() error
	CommandRequest(cmd string, msg *vici.Message) (*vici.Message, error)
	StreamedCommandRequest(cmd string, event string, msg *vici.Message) ([]*vici.Message, error)
}
```

but then vici.Session doesn't satisfy that interface and I needed:

```go
type wrappedSession struct {
	*vici.Session
}

// WrapSession wraps a *vici.Session with a Session object
func WrapSession(s *vici.Session) Session {
	return wrappedSession{s}
}

func (w wrappedSession) StreamedCommandRequest(cmd string, event string, msg *vici.Message) ([]*vici.Message, error) {
	s, err := w.Session.StreamedCommandRequest(cmd, event, msg)
	if err != nil || s == nil {
		return nil, err
	}
	return s.Messages(), nil
}
```

**Comment by enr0n** [comment]
OK, that makes sense. Thank you for explaining. Another option would be to just export the `messages` field so that you can construct `MessageStream` as a struct literal.

With either option, the API might look a little awkward. Having a `NewMessageStream()` function seems weird because there is no real use outside of testing. With the second option, the `MessageStream.Messages()` method becomes redundant, but removing the function would be a breaking change.

Let me think about this a little more, but in any case we will fix your problem.

**Comment by enr0n** [comment]
It's definitely not worth disrupting the API over this, so I will go ahead and merge this.

**Pull request merged**
